FROM alpine:latest

ENV TZ America/Sao_Paulo

RUN apk add --no-cache sqlite curl tzdata tar
RUN ln -s /usr/share/zoneinfo/${TZ} /etc/localtime

COPY scripts/backup.sh /usr/local/bin/backup.sh
COPY scripts/crontab /etc/crontabs/root

RUN chmod +x /usr/local/bin/backup.sh

CMD curl -X POST -H 'Content-type: application/json' --data '{"embeds":[{"title":"Backup","color":0,"description":"Container started."}]}' $DISCORD_BACKUP_WEBHOOK && crond -f
